language: go

go:
  - "1.9"
  - "1.10"

services:
  - mongodb

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)